### ISSUE TITLE
在arclight-forge-1.16-1.0.18.jar 服务器上使用导致铁砧不能附魔

### ISSUE THREAD

**Issue by Bugatti100Peagle** [MarbleGateKeeper/FlowingAgony#1]
在服务器上用会使铁砧不能附魔，就是武器和书都能放进去，就是点不了，拿不出来，单机完全没有问题。服务器端 arclight-forge-1.16-1.0.18.jar。不会导致服务器崩溃，但是铁砧用不了，不只是白门的附魔，包括原版附魔也用不了。

**Comment by MarbleGateKeeper** [comment]
Picture From [MCMOD](https://www.mcmod.cn/class/3872.html)

**Comment by MarbleGateKeeper** [comment]
The problem definitely comes from here:
https://github.com/MarbleGateKeeper/FlowingAgony/blob/3f021d196d642df0b13d464c11450c46b8229644/src/main/java/love/marblegate/flowingagony/eventhandler/enchantment/GloomyEraEnchantmentEventHandler.java#L65-L102
Check it tomorrow.

**Comment by MarbleGateKeeper** [comment]
这个问题只会在Arclight服务端出现，Forge服务端运行正常。
初步估计为Arclight的Mixin Conflict，我会在Arclight那边发Issue。

**Comment by MarbleGateKeeper** [comment]
[1.16.5 白门的奇异附魔：苦痛长河 无法正常使用铁砧附魔 #267](https://github.com/IzzelAliz/Arclight/issues/267)

**Comment by Bugatti100Peagle** [comment]
Alpha版本 flowingagony-1.16.5-beta-0.2.2-arclight.jar 在 arclight-forge-1.16-1.0.18.jar 上测试，附魔问题解决了，原版附魔，其他模组的附魔，白门的附魔都可以用了。

**Comment by MarbleGateKeeper** [comment]
不建议关闭该Issue，等Arclight那边回复再说。不然arclight端少个附魔怪可惜的...

**Comment by MarbleGateKeeper** [comment]
Beta 0.2.4 已经更新。
在 Beta 0.2.4 版本的设置中提供了一个额外的选项 **HYBRID_SERVER_USER** ，现在不需要下载额外的版本了。
请在设置(config/flowingagony-common.toml)中
将 HYBRID_SERVER_USER 设置为 true
该选项会禁用“洗洗再用”附魔并彻底取消其效果
