### ISSUE TITLE
Known Issues

### ISSUE THREAD

**Issue by MarbleGateKeeper** [MarbleGateKeeper/FlowingAgony#10]
By 猫猫丁
学者：高等级会导致收到伤害增加逐渐变成负数，然后实际上变成减伤，20级会变成免伤。再高伤害会变成回血。
侵蚀，高等级原罪侵蚀会变成自己伤害增加，这个伤害能打穿抗性提升5和原罪学者。

by [Silent123261](https://center.mcmod.cn/443411/)
如果同时拥有带药水效果的护甲、混乱原体、异常治疗，则异常治疗会不断触发，刷满3种buff，但是会不停受到攻击（仅有被攻击的效果，没有伤害，非常影响体验）

by [QQ酱455256](https://center.mcmod.cn/455256/)
混乱原体,只要一直刷新效果 就会一直回血 相当于无敌 给帽子附个别的mod里的夜视附魔 然后就能一直刷新有夜视效果 然后一直触发这个的回血,作者能不能加个触发间隔呀

by [伝説](https://center.mcmod.cn/358523/)
混乱原体加上循环的夜视头盔可以无限刷生命不掉血，在加上异常治疗，会无限刷状态，就是偶然会扣一下血，混乱原体介绍写的是加生命上限但是变成了加生命，不知是bug还是特性

### English version:
By 猫猫丁
Scholar of Original Sin & Original Sin Erosion do not support working over the highest level of enchantment level.

by [Silent123261](https://center.mcmod.cn/443411/)
If you also have armor with potion effect, Prototype Chaotic, Exotic Healer, the Exotic Healer will be constantly triggered, brush full of 3 kinds of buffs, but the player will be constantly attacked (only the effect of being attacked, no damage, very impactful experience)

by [QQ酱455256](https://center.mcmod.cn/455256/)
Prototype Chaotic, as long as the effect has been refreshed, it will always return to healing, which is equivalent to invincibility. With a halmet in other mod with night vision enchantment, you can always refresh the effect of night vision, and then always trigger healing. Can author add a trigger interval?

by [伝説](https://center.mcmod.cn/358523/)
Prototype Chaotic plus a night vision helmet of other mod can trigger infinitely healing. Prototype Chaotic's introduction says it adds life cap but actually it becomes healing, Is it a bug or a feature?

**Comment by INooBTooMuch** [comment]
Can these be translated to English because Google Translate isn't accurate enough to understand.
Its not important for me to actually understand them as long ass they are not too harmful to gameplay.

**Comment by MarbleGateKeeper** [comment]
> Can these be translated to English because Google Translate isn't accurate enough to understand. Its not important for me to actually understand them as long ass they are not too harmful to gameplay.

Thanks for your advice.

**Comment by MarbleGateKeeper** [comment]
Considering this mod is about to discontinue and only has limited support now, problem 1, 2 and 3 won't be fixed.
