### ISSUE TITLE
纸脑魔咒 崩溃

### ISSUE THREAD

**Issue by Kasualix** [MarbleGateKeeper/FlowingAgony#11]
坠机报告：https://pastebin.ubuntu.com/p/xyQjQJ3Y6t/
最新日志：https://pastebin.ubuntu.com/p/fbqp4N7Csk/

**Comment by MarbleGateKeeper** [comment]
看完了。请去向RoadRunner提交Issue，坠机报告中并无任何相关本模组相关内容。
纸脑附魔并不对AI进行任何修改，也不直接操作AI。
