### ISSUE TITLE
Crash relavent to this mod / 怀疑此模组导致崩溃

### ISSUE THREAD

**Issue by Water-Moon** [MarbleGateKeeper/FlowingAgony#3]
运行环境/Environment: Minecraft 1.16.5 + Forge 36.1.25，服务端/Dedicated Server

错误描述/description: 并不知道实际的触发原理，但在某些玩家射箭之后服务器就会发生崩溃/The underlying cause is unclear, but it appears crash is caused by some player shooting arrow.

没有完全确定的证据可以表明是由该模组造成的，但由于错误堆栈里面提到调用了该模组的某个方法，因此怀疑与此模组有关/No enough evidence to claim it's solely caused by this mod, but, methods from this mod were in the stack trace, therefore it could be relevant.

[崩溃报告/crash repeort](https://github.com/MarbleGateKeeper/FlowingAgony/files/6604010/crash-2021-06-06_17.09.28-server.txt)

**Comment by MarbleGateKeeper** [comment]
找到原因了，我是真没想到有玩家把附魔到直接攻击的武器上附魔给加到投射物武器上去.....这个是原版附魔台和铁砧做不到的。
正在修复Bug，请稍等。
实际上能触发的不止这一个附魔，感谢反馈。

**Comment by MarbleGateKeeper** [comment]
@Water-Moon 
已经修复，应该不会再出现这个问题了，你可以在
https://www.curseforge.com/minecraft/mc-mods/marblegates-exotic-enchantment-flowing-agony/files
下载 Flowing Agony Beta-0.2.4

如果CurseForge上传的文件还没通过审核
你也可以在 https://www.mcmod.cn/download/3872.html
下载 flowingagony-1.16.5-beta-0.2.4.jar
