### ISSUE TITLE
Server Crash with Deathpunk Enchant

### ISSUE THREAD

**Issue by darkphan** [MarbleGateKeeper/FlowingAgony#4]
Crash Log: https://gist.github.com/darkphan/10331cd6a29c5561c6eb510510a31d99
Mod Version: flowingagony-1.16.5-beta-0.2.4
Forge Version: 36.1.32

**Comment by MarbleGateKeeper** [comment]
Bug is fixed. Thanks For Your Report~❤
You can download it at https://www.curseforge.com/minecraft/mc-mods/marblegates-exotic-enchantment-flowing-agony/files/all
If curseforge is processing the file, you can download here: https://drive.google.com/file/d/14DauL4nc_GyZYwWPyFbe7Av0j-9Qk5NX/view?usp=sharing
