### ISSUE TITLE
StackOverflow when attacked by Guardians with Drowning Phobia

### ISSUE THREAD

**Issue by yanang007** [MarbleGateKeeper/FlowingAgony#9]
Game version: 1.18.2
Forge version: 40.1.59
Mod version: 1.2.5

This is vanilla **_Guardian#hurt_**, it will reflect non magic damage and deal thorn damage to the damage source, which will again trigger the **_Drowning Phobia_**. A possible workaroud is to set **_FlowingAgonyMobtoMobDamageSource_** as **_magic_** damage, but a special check for it may be a better solution.
```
public boolean hurt(DamageSource p_32820_, float p_32821_) {
      if (!this.isMoving() && !p_32820_.isMagic() && p_32820_.getDirectEntity() instanceof LivingEntity) {
         LivingEntity livingentity = (LivingEntity)p_32820_.getDirectEntity();
         if (!p_32820_.isExplosion()) {
            livingentity.hurt(DamageSource.thorns(this), 2.0F);
         }
      }

      if (this.randomStrollGoal != null) {
         this.randomStrollGoal.trigger();
      }

      return super.hurt(p_32820_, p_32821_);
   }
```

Step to reproduce:
1. Get a low tier helmet(e.g., leather helmet)
2. Enchant it with Drowning Phobia
3. Summon 3 Guardians
4. Swim and get attacked by Guardians

Crash report:
[Crash report from dedicated server (Arclight server, may contain irrelevant info)](https://paste.ubuntu.com/p/X6Sk6m9V7Q/)
[Crash report from local game](https://paste.ubuntu.com/p/8BBNHXjySD/)

**Comment by MarbleGateKeeper** [comment]
Please use [1.2.6](https://www.curseforge.com/minecraft/mc-mods/marblegates-exotic-enchantment-flowing-agony/files/3902228). Thank you for detailed report!

**Comment by yanang007** [comment]
Wow, thanks for your quick response! That should fix this. Thank you for the amazing mod!
